FROM node

# Este es el directorio de trabajo
WORKDIR /app/sheet-music-player

# Se copia el archivo de dependencia y el código fuente al contenedor
COPY package.json package-lock.json /app/sheet-music-player/
COPY . /app/sheet-music-player/

# Se instalan las dependencias
RUN npm install

# Puerto
EXPOSE 3000

CMD [ "npm", "run", "dev" ]